### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by ukiran03** [AmaiKinono/clue#4]
Such a cool little idea! 
Please consider adding it to MELPA. Thank you.

**Comment by AmaiKinono** [comment]
I'm not sure on this. I haven't been using this package for a long time, so maybe I'm not ready to make it through the MELPA review and deal with the added issues from new users.

For now I'd suggest you use git submodule or some package manager that supports packages from GitHub to get this package into your config.

**Comment by ukiran03** [comment]
That's fine, thank you. By the way, thanks for the TV series recommendation.
